import {SCRATCH_CATEGORIES,DEFAULT_LESSONS,DEFAULT_LEVELS,DEFAULT_THEME} from '../data/content-seed.js';
const K={users:'scratchAR.users',lessons:'scratchAR.lessons',levels:'scratchAR.levels',media:'scratchAR.media',theme:'scratchAR.theme',auth:'scratchAR.adminAuth',activity:'scratchAR.activity'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}, write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const lines=v=>String(v||'').split('\n').map(x=>x.trim()).filter(Boolean); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let users=[],lessons=[],levels=[],media=[],theme={},toastTimer;
async function hash(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2400)}
function log(action){const a=read(K.activity,[]);a.unshift({action,at:new Date().toISOString()});write(K.activity,a.slice(0,60))}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),300)}
function fmt(d){return d?new Date(d).toLocaleString('th-TH'):'-'}
function ensureSeed(force=false){if(force||!localStorage.getItem(K.lessons))write(K.lessons,structuredClone(DEFAULT_LESSONS));if(force||!localStorage.getItem(K.levels))write(K.levels,structuredClone(DEFAULT_LEVELS));if(!localStorage.getItem(K.media))write(K.media,[]);if(!localStorage.getItem(K.theme))write(K.theme,DEFAULT_THEME)}
function load(){users=read(K.users,[]);lessons=read(K.lessons,[]);levels=read(K.levels,[]);media=read(K.media,[]);theme={...DEFAULT_THEME,...read(K.theme,{})}}
function authMode(){const auth=read(K.auth,null);if(!auth){$('#login-title').textContent='ตั้งค่าผู้ดูแลระบบ';$('#login-help').textContent='ครั้งแรก กรุณาสร้างชื่อผู้ดูแลและรหัสผ่านเฉพาะของครู';$('#confirm-wrap').classList.remove('hidden');$('#login-submit').textContent='สร้างบัญชีผู้ดูแล';return 'setup'}$('#login-title').textContent='เข้าสู่ระบบผู้ดูแล';$('#login-help').textContent='สำหรับครูหรือผู้ดูแลระบบเท่านั้น';$('#confirm-wrap').classList.add('hidden');$('#login-submit').textContent='เข้าสู่ระบบ';$('#username').value=auth.username||'';return 'login'}
let mode=authMode();
$('#login-form').onsubmit=async e=>{e.preventDefault();const username=$('#username').value.trim(),password=$('#password').value,confirm=$('#confirm-password').value;if(mode==='setup'){if(username.length<3)return $('#login-error').textContent='ชื่อผู้ดูแลต้องมีอย่างน้อย 3 ตัวอักษร';if(password.length<6)return $('#login-error').textContent='รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร';if(password!==confirm)return $('#login-error').textContent='ยืนยันรหัสผ่านไม่ตรงกัน';write(K.auth,{username,passwordHash:await hash(password),createdAt:new Date().toISOString()});ensureSeed(false);sessionStorage.setItem('scratchAR.admin','yes');log('สร้างบัญชีผู้ดูแล');showApp();return}const auth=read(K.auth,{});if(username===auth.username&&await hash(password)===auth.passwordHash){sessionStorage.setItem('scratchAR.admin','yes');showApp()}else $('#login-error').textContent='ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'};
function showApp(){ensureSeed(false);load();$('#login').classList.add('hidden');$('#admin-app').classList.remove('hidden');renderAll()}
if(sessionStorage.getItem('scratchAR.admin')==='yes'&&read(K.auth,null))showApp();
$('#logout').onclick=()=>{sessionStorage.removeItem('scratchAR.admin');location.reload()};
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.add('hidden'));$('#view-'+b.dataset.view).classList.remove('hidden')});
function renderDashboard(){const completed=users.reduce((a,u)=>a+Number(u.progress?.completedLevels||0),0);$('#summary').innerHTML=[['👥','ผู้เล่น',users.length],['📚','บทเรียน',lessons.length],['🎮','ด่าน',levels.length],['🖼️','สื่อ',media.length],['✅','ด่านสำเร็จรวม',completed]].map(x=>`<div class="summary-card"><span>${x[0]}</span><strong>${x[2]}</strong><small>${x[1]}</small></div>`).join('');$('#coverage').innerHTML=SCRATCH_CATEGORIES.map(c=>`<div class="coverage-row"><i style="background:${c.color}"></i><span>${c.name}</span><b>${lessons.some(l=>l.category===c.id)?'✓':'–'}</b></div>`).join('');$('#recent-activity').innerHTML=read(K.activity,[]).slice(0,8).map(a=>`<p><strong>${esc(a.action)}</strong><small>${fmt(a.at)}</small></p>`).join('')||'<p class="muted">ยังไม่มีกิจกรรม</p>';$('#header-school').textContent=theme.schoolName||theme.systemName}
function fillSelects(){const opts=['foundation','project',...SCRATCH_CATEGORIES.map(c=>c.id)];$('#lesson-category').innerHTML=opts.map(x=>`<option value="${x}">${x}</option>`).join('');$('#lesson-filter').innerHTML='<option value="">ทุกหมวด</option>'+opts.map(x=>`<option value="${x}">${x}</option>`).join('');$('#level-lesson').innerHTML=lessons.slice().sort((a,b)=>a.order-b.order).map(l=>`<option value="${l.id}">${l.order}. ${esc(l.title)}</option>`).join('');$('#level-prerequisite').innerHTML='<option value="">ไม่กำหนด</option>'+levels.slice().sort((a,b)=>a.order-b.order).map(l=>`<option value="${l.id}">ด่าน ${l.order}: ${esc(l.title)}</option>`).join('');const types=['block-order','quiz','matching','hotspot','multi-script','debug','builder','project'];$('#level-type-filter').innerHTML='<option value="">ทุกแม่แบบ</option>'+types.map(x=>`<option>${x}</option>`).join('')}
function clearLesson(){ $('#lesson-form').reset();$('#lesson-id').value='';$('#lesson-order').value=Math.max(0,...lessons.map(x=>+x.order||0))+1;$('#lesson-published').checked=true;$('#lesson-media-preview').textContent='พื้นที่ตัวอย่างสื่อ'}
$('#new-lesson').onclick=clearLesson;$('#clear-lesson').onclick=clearLesson;
$('#lesson-form').onsubmit=e=>{e.preventDefault();const id=$('#lesson-id').value||`lesson-${Date.now()}`;const o={id,order:+$('#lesson-order').value,title:$('#lesson-title').value.trim(),category:$('#lesson-category').value,summary:$('#lesson-summary').value.trim(),objectives:lines($('#lesson-objectives').value),content:$('#lesson-content').value.trim(),imageUrl:$('#lesson-image').value.trim(),videoUrl:$('#lesson-video').value.trim(),audioUrl:$('#lesson-audio').value.trim(),published:$('#lesson-published').checked,updatedAt:new Date().toISOString()};const i=lessons.findIndex(x=>x.id===id);i>=0?lessons[i]=o:lessons.push(o);write(K.lessons,lessons);log(`บันทึกบทเรียน: ${o.title}`);clearLesson();renderAll();toast('บันทึกบทเรียนแล้ว')};
$('#duplicate-lesson').onclick=()=>{$('#lesson-id').value='';$('#lesson-title').value+=' (สำเนา)';toast('พร้อมบันทึกเป็นบทเรียนใหม่')};
function editLesson(id){const l=lessons.find(x=>x.id===id);if(!l)return;$('#lesson-id').value=l.id;$('#lesson-order').value=l.order;$('#lesson-title').value=l.title;$('#lesson-category').value=l.category;$('#lesson-summary').value=l.summary||'';$('#lesson-objectives').value=(l.objectives||[]).join('\n');$('#lesson-content').value=l.content||'';$('#lesson-image').value=l.imageUrl||'';$('#lesson-video').value=l.videoUrl||'';$('#lesson-audio').value=l.audioUrl||'';$('#lesson-published').checked=l.published!==false;scrollTo({top:0,behavior:'smooth'})}
function renderLessons(){const q=$('#lesson-search')?.value.toLowerCase()||'',f=$('#lesson-filter')?.value||'';$('#lesson-list').innerHTML=lessons.slice().sort((a,b)=>a.order-b.order).filter(l=>(!f||l.category===f)&&`${l.title} ${l.summary} ${l.category}`.toLowerCase().includes(q)).map(l=>`<article class="item-card"><div><span class="badge">${l.order}</span><strong>${esc(l.title)}</strong><small>${esc(l.category)} • ${l.published?'เผยแพร่':'ฉบับร่าง'}</small></div><p>${esc(l.summary||'')}</p><div class="actions"><button data-edit-lesson="${l.id}" class="small">แก้ไข</button><button data-copy-lesson="${l.id}" class="small secondary">สำเนา</button><button data-delete-lesson="${l.id}" class="small danger">ลบ</button></div></article>`).join('')||'<p class="muted">ไม่พบบทเรียน</p>';$$('[data-edit-lesson]').forEach(b=>b.onclick=()=>editLesson(b.dataset.editLesson));$$('[data-copy-lesson]').forEach(b=>b.onclick=()=>{editLesson(b.dataset.copyLesson);$('#lesson-id').value='';$('#lesson-title').value+=' (สำเนา)'});$$('[data-delete-lesson]').forEach(b=>b.onclick=()=>{if(confirm('ลบบทเรียนนี้หรือไม่?')){lessons=lessons.filter(x=>x.id!==b.dataset.deleteLesson);write(K.lessons,lessons);renderAll();toast('ลบบทเรียนแล้ว')}})}
$('#lesson-search').oninput=renderLessons;$('#lesson-filter').onchange=renderLessons;
function clearLevel(){ $('#level-form').reset();$('#level-id').value='';$('#level-order').value=Math.max(0,...levels.map(x=>+x.order||0))+1;$('#level-time').value=60;$('#level-hearts').value=3;$('#level-score').value=100;$('#star-three').value=30;$('#star-two').value=45;$('#star-one').value=60;$('#level-published').checked=true;$('#level-media-preview').textContent='พื้นที่ตัวอย่างสื่อด่าน'}
$('#new-level').onclick=clearLevel;
$('#level-form').onsubmit=e=>{e.preventDefault();const id=$('#level-id').value||`level-${Date.now()}`;const o={id,order:+$('#level-order').value,title:$('#level-title').value.trim(),type:$('#level-type').value,lessonId:[...$('#level-lesson').selectedOptions][0]?.value||'',requiredLessonIds:[...$('#level-lesson').selectedOptions].map(o=>o.value),prerequisiteLevelId:$('#level-prerequisite').value,difficulty:+$('#level-difficulty').value,prompt:$('#level-prompt').value.trim(),blocks:lines($('#level-blocks').value),answer:lines($('#level-answer').value),timeLimit:+$('#level-time').value,hearts:+$('#level-hearts').value,maxScore:+$('#level-score').value,stars:{three:+$('#star-three').value,two:+$('#star-two').value,one:+$('#star-one').value},imageUrl:$('#level-image').value.trim(),audioUrl:$('#level-audio').value.trim(),published:$('#level-published').checked,updatedAt:new Date().toISOString()};const i=levels.findIndex(x=>x.id===id);i>=0?levels[i]=o:levels.push(o);write(K.levels,levels);log(`บันทึกด่าน: ${o.title}`);clearLevel();renderAll();toast('บันทึกด่านแล้ว')};
$('#duplicate-level').onclick=()=>{$('#level-id').value='';$('#level-title').value+=' (สำเนา)';toast('พร้อมบันทึกเป็นด่านใหม่')};
function editLevel(id){const l=levels.find(x=>x.id===id);if(!l)return;$('#level-id').value=l.id;$('#level-order').value=l.order;$('#level-title').value=l.title;$('#level-type').value=l.type;[...$('#level-lesson').options].forEach(o=>o.selected=(l.requiredLessonIds||[l.lessonId]).includes(o.value));$('#level-prerequisite').value=l.prerequisiteLevelId||'';$('#level-difficulty').value=l.difficulty||1;$('#level-prompt').value=l.prompt||'';$('#level-blocks').value=(l.blocks||[]).join('\n');$('#level-answer').value=(l.answer||[]).join('\n');$('#level-time').value=l.timeLimit||0;$('#level-hearts').value=l.hearts||3;$('#level-score').value=l.maxScore||100;$('#star-three').value=l.stars?.three||0;$('#star-two').value=l.stars?.two||0;$('#star-one').value=l.stars?.one||0;$('#level-image').value=l.imageUrl||'';$('#level-audio').value=l.audioUrl||'';$('#level-published').checked=l.published!==false;scrollTo({top:0,behavior:'smooth'})}
function renderLevels(){const q=$('#level-search')?.value.toLowerCase()||'',f=$('#level-type-filter')?.value||'';$('#level-list').innerHTML=levels.slice().sort((a,b)=>a.order-b.order).filter(l=>(!f||l.type===f)&&`${l.title} ${l.prompt} ${l.type}`.toLowerCase().includes(q)).map(l=>`<article class="item-card"><div><span class="badge">${l.order}</span><strong>${esc(l.title)}</strong><small>${l.type} • ยาก ${l.difficulty} • ${l.published?'เผยแพร่':'ฉบับร่าง'}</small></div><p>${esc(l.prompt||'')}</p><div class="block-tags">${(l.blocks||[]).slice(0,4).map(x=>`<code>${esc(x)}</code>`).join('')}</div><div class="actions"><button data-edit-level="${l.id}" class="small">แก้ไข</button><button data-preview-level="${l.id}" class="small secondary">ตัวอย่าง</button><button data-delete-level="${l.id}" class="small danger">ลบ</button></div></article>`).join('')||'<p class="muted">ไม่พบด่าน</p>';$$('[data-edit-level]').forEach(b=>b.onclick=()=>editLevel(b.dataset.editLevel));$$('[data-preview-level]').forEach(b=>b.onclick=()=>showLevel(levels.find(x=>x.id===b.dataset.previewLevel)));$$('[data-delete-level]').forEach(b=>b.onclick=()=>{if(confirm('ลบด่านนี้หรือไม่?')){levels=levels.filter(x=>x.id!==b.dataset.deleteLevel);write(K.levels,levels);renderAll();toast('ลบด่านแล้ว')}})}
$('#level-search').oninput=renderLevels;$('#level-type-filter').onchange=renderLevels;$('#preview-level').onclick=()=>showLevel({title:$('#level-title').value||'ตัวอย่างด่าน',prompt:$('#level-prompt').value,blocks:lines($('#level-blocks').value),imageUrl:$('#level-image').value});
function showLevel(l){$('#dialog-content').innerHTML=`<h2>${esc(l.title)}</h2>${l.imageUrl?`<img src="${esc(l.imageUrl)}">`:''}<p>${esc(l.prompt||'')}</p><div class="preview-blocks">${(l.blocks||[]).map(x=>`<div>${esc(x)}</div>`).join('')}</div>`;$('#preview-dialog').showModal()}
$('#close-dialog').onclick=()=>$('#preview-dialog').close();
function previewMedia(inputId,targetId){const url=$('#'+inputId).value.trim(),box=$('#'+targetId);box.innerHTML=url?`<img src="${esc(url)}" alt="preview" onerror="this.parentElement.textContent='ไม่สามารถโหลดรูปได้ โปรดตรวจ URL'">`:'กรุณาวาง URL รูปภาพ'}
$$('[data-preview]').forEach(b=>b.onclick=()=>previewMedia(b.dataset.preview,b.dataset.preview.startsWith('lesson')?'lesson-media-preview':'level-media-preview'));
$$('[data-play]').forEach(b=>b.onclick=()=>{const url=$('#'+b.dataset.play).value.trim();if(!url)return toast('กรุณาวาง URL เสียง');new Audio(url).play().catch(()=>toast('ไม่สามารถเล่นเสียงจาก URL นี้ได้'))});
$('#media-type').onchange=$('#media-url').oninput=()=>{const type=$('#media-type').value,url=$('#media-url').value.trim(),box=$('#media-preview');if(!url)return box.textContent='พื้นที่ตัวอย่างสื่อ';box.innerHTML=type==='image'?`<img src="${esc(url)}">`:type==='audio'?`<audio controls src="${esc(url)}"></audio>`:type==='video'?`<video controls src="${esc(url)}"></video>`:`<a href="${esc(url)}" target="_blank">เปิดลิงก์</a>`};
$('#new-media').onclick=()=>{$('#media-form').reset();$('#media-id').value='';$('#media-preview').textContent='พื้นที่ตัวอย่างสื่อ'};
$('#media-form').onsubmit=e=>{e.preventDefault();const id=$('#media-id').value||`media-${Date.now()}`;const o={id,name:$('#media-name').value.trim(),type:$('#media-type').value,url:$('#media-url').value.trim(),tags:lines($('#media-tags').value.replaceAll(',','\n')),note:$('#media-note').value.trim(),updatedAt:new Date().toISOString()};const i=media.findIndex(x=>x.id===id);i>=0?media[i]=o:media.push(o);write(K.media,media);log(`บันทึกสื่อ: ${o.name}`);$('#new-media').click();renderAll();toast('บันทึกสื่อแล้ว')};
function renderMedia(){const q=$('#media-search')?.value.toLowerCase()||'';$('#media-list').innerHTML=media.filter(m=>`${m.name} ${m.url} ${(m.tags||[]).join(' ')}`.toLowerCase().includes(q)).map(m=>`<article class="media-card"><div class="media-thumb">${m.type==='image'?`<img src="${esc(m.url)}">`:m.type==='audio'?'🔊':m.type==='video'?'🎬':'🔗'}</div><strong>${esc(m.name)}</strong><small>${esc(m.type)} • ${(m.tags||[]).map(esc).join(', ')}</small><div class="actions"><button data-copy-url="${esc(m.url)}" class="small">คัดลอก URL</button><button data-edit-media="${m.id}" class="small secondary">แก้ไข</button><button data-delete-media="${m.id}" class="small danger">ลบ</button></div></article>`).join('')||'<p class="muted">ยังไม่มีสื่อ</p>';$$('[data-copy-url]').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.copyUrl).then(()=>toast('คัดลอก URL แล้ว')));$$('[data-edit-media]').forEach(b=>b.onclick=()=>{const m=media.find(x=>x.id===b.dataset.editMedia);$('#media-id').value=m.id;$('#media-name').value=m.name;$('#media-type').value=m.type;$('#media-url').value=m.url;$('#media-tags').value=(m.tags||[]).join(', ');$('#media-note').value=m.note||'';$('#media-url').dispatchEvent(new Event('input'))});$$('[data-delete-media]').forEach(b=>b.onclick=()=>{if(confirm('ลบรายการสื่อนี้หรือไม่?')){media=media.filter(x=>x.id!==b.dataset.deleteMedia);write(K.media,media);renderMedia()}})}
$('#media-search').oninput=renderMedia;
function renderUsers(){const q=$('#user-search')?.value.toLowerCase()||'';$('#users-body').innerHTML=users.filter(u=>`${u.nickname} ${u.classroom} ${u.studentNumber}`.toLowerCase().includes(q)).map(u=>`<tr><td>${u.avatarEmoji||'👤'} <strong>${esc(u.nickname||'-')}</strong></td><td>${esc(u.classroom||'-')} / ${esc(u.studentNumber||'-')}</td><td>${Number(u.progress?.totalScore||0)}</td><td>${Number(u.progress?.totalStars||0)}</td><td>${esc(u.progress?.lastLevel||'-')}</td><td>${fmt(u.lastPlayedAt)}</td><td><button data-reset-user="${u.id}" class="small">รีเซ็ต</button> <button data-delete-user="${u.id}" class="small danger">ลบ</button></td></tr>`).join('')||'<tr><td colspan="7">ยังไม่มีข้อมูลผู้เล่น</td></tr>';$$('[data-reset-user]').forEach(b=>b.onclick=()=>{const u=users.find(x=>x.id===b.dataset.resetUser);if(u&&confirm('รีเซ็ตความก้าวหน้าของผู้เล่นนี้หรือไม่?')){u.progress={totalScore:0,totalStars:0,completedLevels:0};write(K.users,users);renderAll()}});$$('[data-delete-user]').forEach(b=>b.onclick=()=>{if(confirm('ลบผู้เล่นนี้หรือไม่?')){users=users.filter(x=>x.id!==b.dataset.deleteUser);write(K.users,users);renderAll()}})}
$('#user-search').oninput=renderUsers;$('#export-users').onclick=()=>download('scratch-ar-users.json',JSON.stringify(users,null,2));
function syncThemeForm(){$('#system-name').value=theme.systemName;$('#school-name').value=theme.schoolName;$('#accent').value=theme.accent;$('#font-scale').value=theme.fontScale;$('#card-opacity').value=theme.cardOpacity;$('#blur').value=theme.blur;$('#radius').value=theme.cornerRadius;$('#show-admin-link').checked=theme.showAdminLink;$('#allow-profiles').checked=theme.allowProfiles;$('#auto-speak').checked=theme.autoSpeak;updateThemePreview()}
function updateThemePreview(){const t={accent:$('#accent').value,fontScale:+$('#font-scale').value,cardOpacity:+$('#card-opacity').value,blur:+$('#blur').value,cornerRadius:+$('#radius').value};$('#opacity-output').textContent=Math.round(t.cardOpacity*100)+'%';$('#blur-output').textContent=t.blur+'px';$('#radius-output').textContent=t.cornerRadius+'px';const p=$('#theme-preview');p.style.setProperty('--accent',t.accent);p.style.setProperty('--opacity',t.cardOpacity);p.style.setProperty('--blur',t.blur+'px');p.style.setProperty('--radius',t.cornerRadius+'px');p.style.fontSize=t.fontScale+'rem'}
['accent','font-scale','card-opacity','blur','radius'].forEach(id=>$('#'+id).oninput=updateThemePreview);
$('#theme-form').onsubmit=e=>{e.preventDefault();theme={...theme,systemName:$('#system-name').value.trim(),schoolName:$('#school-name').value.trim(),accent:$('#accent').value,fontScale:+$('#font-scale').value,cardOpacity:+$('#card-opacity').value,blur:+$('#blur').value,cornerRadius:+$('#radius').value,showAdminLink:$('#show-admin-link').checked,allowProfiles:$('#allow-profiles').checked,autoSpeak:$('#auto-speak').checked};write(K.theme,theme);log('ปรับแต่ง UI');toast('บันทึก UI แล้ว');renderDashboard()};
function renderReports(){const rows=users.map(u=>({name:u.nickname||'-',classroom:u.classroom||'-',score:+u.progress?.totalScore||0,stars:+u.progress?.totalStars||0,completed:+u.progress?.completedLevels||0,last:fmt(u.lastPlayedAt)}));$('#report-content').innerHTML=`<h3>สรุปผลผู้เรียน</h3><table><thead><tr><th>ชื่อ</th><th>ชั้น</th><th>คะแนน</th><th>ดาว</th><th>ด่านสำเร็จ</th><th>ล่าสุด</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.classroom)}</td><td>${r.score}</td><td>${r.stars}</td><td>${r.completed}</td><td>${r.last}</td></tr>`).join('')}</tbody></table><h3>สถานะเนื้อหา</h3><p>บทเรียนเผยแพร่ ${lessons.filter(x=>x.published).length}/${lessons.length} • ด่านเผยแพร่ ${levels.filter(x=>x.published).length}/${levels.length}</p>`}
$('#print-report').onclick=()=>print();$('#export-report').onclick=()=>{const csv=['ชื่อ,ชั้น,คะแนน,ดาว,ด่านสำเร็จ',...users.map(u=>[u.nickname,u.classroom,u.progress?.totalScore||0,u.progress?.totalStars||0,u.progress?.completedLevels||0].map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(','))].join('\n');download('scratch-ar-report.csv','\uFEFF'+csv,'text/csv;charset=utf-8')};
$('#backup-all').onclick=()=>{const out={version:2,exportedAt:new Date().toISOString(),users,lessons,levels,media,theme,auth:read(K.auth,null)};download(`scratch-ar-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(out,null,2))};
$('#restore-file').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(!confirm('กู้คืนและเขียนทับข้อมูลปัจจุบันหรือไม่?'))return;for(const [k,v] of [['users',d.users],['lessons',d.lessons],['levels',d.levels],['media',d.media],['theme',d.theme],['auth',d.auth]])if(v!==undefined)write(K[k],v);location.reload()}catch{alert('ไฟล์ Backup ไม่ถูกต้อง')}};
$('#import-content').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(Array.isArray(d.lessons))write(K.lessons,d.lessons);if(Array.isArray(d.levels))write(K.levels,d.levels);if(Array.isArray(d.media))write(K.media,d.media);load();renderAll();toast('นำเข้าข้อมูลแล้ว')}catch{alert('ไฟล์ JSON ไม่ถูกต้อง')}};
$('#clear-progress').onclick=()=>{if(confirm('ล้างคะแนนและดาวของผู้เล่นทั้งหมดหรือไม่?')){users.forEach(u=>u.progress={totalScore:0,totalStars:0,completedLevels:0});write(K.users,users);renderAll()}};
$('#clear-all').onclick=()=>{if(confirm('ล้างข้อมูลเนื้อหา ด่าน สื่อ ผู้เล่น และการตั้งค่าทั้งหมดหรือไม่?')){Object.values(K).forEach(k=>localStorage.removeItem(k));sessionStorage.clear();location.reload()}};
$('#seed-content').onclick=()=>{if(confirm('คืนค่าเนื้อหาและด่านแม่แบบ Scratch ทั้งหมดหรือไม่? ข้อมูลบทเรียนและด่านปัจจุบันจะถูกแทนที่')){ensureSeed(true);log('คืนค่าแม่แบบ Scratch');load();renderAll();toast('คืนค่าแม่แบบแล้ว')}};
function syncSecurity(){const a=read(K.auth,{});$('#security-username').value=a.username||''}
$('#security-form').onsubmit=async e=>{e.preventDefault();const a=read(K.auth,{}),old=$('#old-password').value,neu=$('#new-password').value,con=$('#new-password-confirm').value;if(await hash(old)!==a.passwordHash)return toast('รหัสผ่านเดิมไม่ถูกต้อง');if(neu&&neu.length<6)return toast('รหัสผ่านใหม่สั้นเกินไป');if(neu!==con)return toast('ยืนยันรหัสผ่านใหม่ไม่ตรงกัน');write(K.auth,{...a,username:$('#security-username').value.trim()||a.username,passwordHash:neu?await hash(neu):a.passwordHash,updatedAt:new Date().toISOString()});$('#security-form').reset();syncSecurity();toast('เปลี่ยนข้อมูลเข้าสู่ระบบแล้ว')};
function renderAll(){load();fillSelects();renderDashboard();renderLessons();renderLevels();renderMedia();renderUsers();syncThemeForm();renderReports();syncSecurity()}
