const configured=()=>{const c=window.SAR_FIREBASE_CONFIG||{};return !!(c.apiKey&&!String(c.apiKey).includes('PUT_YOUR')&&c.projectId&&!String(c.projectId).includes('PUT_YOUR'))};
async function sha256(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
class CloudService{
 constructor(){this.enabled=false;this.db=null;this.auth=null;this.schoolId='default-school'}
 async init(){if(!window.firebase||!configured()||window.SAR_CLOUD_OPTIONS?.enabled===false){console.warn('Firebase ยังไม่ได้ตั้งค่า ใช้ localStorage ชั่วคราว');return false}try{if(!firebase.apps.length)firebase.initializeApp(window.SAR_FIREBASE_CONFIG);this.auth=firebase.auth();this.db=firebase.firestore();this.schoolId=window.SAR_CLOUD_OPTIONS?.schoolId||'default-school';this.enabled=true;await this.db.enablePersistence({synchronizeTabs:true}).catch(()=>{});return true}catch(e){console.error('Firebase init failed',e);return false}}
 async playerEmail(name){const h=await sha256(name.trim().toLowerCase());return `p-${h.slice(0,32)}@${window.SAR_CLOUD_OPTIONS?.playerEmailDomain||'players.scratchar.app'}`}
 playerPassword(pin){return `SaA!${pin}#2026`}
 userRef(uid){return this.db.collection('schools').doc(this.schoolId).collection('players').doc(uid)}
 async registerPlayer(profile,pin){const email=await this.playerEmail(profile.name);const cred=await this.auth.createUserWithEmailAndPassword(email,this.playerPassword(pin));const u={...profile,id:cred.user.uid,uid:cred.user.uid,usernameKey:(await sha256(profile.name.trim().toLowerCase())).slice(0,32),createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};delete u.pin;await this.userRef(cred.user.uid).set(u);return {...profile,id:cred.user.uid}}
 async loginPlayer(name,pin){const email=await this.playerEmail(name);const cred=await this.auth.signInWithEmailAndPassword(email,this.playerPassword(pin));const snap=await this.userRef(cred.user.uid).get();if(!snap.exists)throw new Error('ไม่พบข้อมูลผู้เล่น');return {...snap.data(),id:cred.user.uid,pin}}
 async savePlayer(user){if(!this.enabled||!user?.id)return;const clean={...user,uid:user.id,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};delete clean.pin;await this.userRef(user.id).set(clean,{merge:true})}
 async deletePlayer(user){if(!this.enabled||!user?.id)return;await this.userRef(user.id).delete();if(this.auth.currentUser?.uid===user.id)await this.auth.currentUser.delete()}
 async listPlayers(){if(!this.enabled)return [];const s=await this.db.collection('schools').doc(this.schoolId).collection('players').orderBy('score','desc').limit(500).get();return s.docs.map(d=>({...d.data(),id:d.id}))}
 async saveEvent(event){if(!this.enabled)return;await this.db.collection('schools').doc(this.schoolId).collection('events').add({...event,serverAt:firebase.firestore.FieldValue.serverTimestamp()})}
 async loadShared(){if(!this.enabled)return {};const [content,settings]=await Promise.all([this.db.collection('schools').doc(this.schoolId).collection('system').doc('content').get(),this.db.collection('schools').doc(this.schoolId).collection('system').doc('settings').get()]);return {content:content.exists?content.data():null,settings:settings.exists?settings.data():null}}
 async saveShared(data){if(!this.enabled)return;const base=this.db.collection('schools').doc(this.schoolId).collection('system');if(data.lessons||data.levels)await base.doc('content').set({lessons:data.lessons||[],levels:data.levels||[],updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});if(data.settings)await base.doc('settings').set({...data.settings,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}
 async adminLogin(identifier,password){if(!this.enabled)throw new Error('ยังไม่ได้ตั้งค่า Firebase');const email=identifier.includes('@')?identifier:(window.SAR_CLOUD_OPTIONS?.adminEmail||'');if(!email)throw new Error('กรุณาใส่อีเมลผู้ดูแลใน firebase-config.js');const cred=await this.auth.signInWithEmailAndPassword(email,password);const a=await this.db.collection('admins').doc(cred.user.uid).get();if(!a.exists||a.data().role!=='admin'){await this.auth.signOut();throw new Error('บัญชีนี้ไม่มีสิทธิ์ผู้ดูแล')}return true}
 async signOut(){if(this.enabled)await this.auth.signOut()}
}
export const cloud=new CloudService();
