import {setupTheme,levels,lessons,esc,SCRATCH_CATEGORIES} from './common.js';
import {speak,speakMixed,installSpeechControls} from './speech.js';
setupTheme();installSpeechControls();
const params=new URLSearchParams(location.search),id=params.get('id');const allLevels=levels(),allLessons=lessons();const level=allLevels.find(x=>x.id===id)||allLevels[0];const lesson=allLessons.find(x=>x.id===level.lessonId);const lessonProgress=JSON.parse(localStorage.getItem('scratchAR.lessonProgress')||'{}');const levelProgress=JSON.parse(localStorage.getItem('scratchAR.levelProgress')||'{}');const requiredLessonIds=Array.isArray(level.requiredLessonIds)&&level.requiredLessonIds.length?level.requiredLessonIds:(level.lessonId?[level.lessonId]:[]);const missingLessons=requiredLessonIds.filter(x=>!lessonProgress[x]?.completed);const prerequisiteMissing=level.prerequisiteLevelId&&!levelProgress[level.prerequisiteLevelId]?.completed;const game=document.querySelector('#game');let selected=[],hearts=level.hearts||3,start=Date.now();
const categoryOf=t=>{t=t.toLowerCase();for(const c of SCRATCH_CATEGORIES)if(c.blocks.some(b=>t.includes(b.split('(')[0].trim().toLowerCase())))return c.id;if(/green flag|key pressed|broadcast|receive/.test(t))return'events';if(/repeat|forever|wait|if |clone|stop/.test(t))return'control';if(/say|think|costume|backdrop|size|show|hide/.test(t))return'looks';if(/sound|volume/.test(t))return'sound';if(/touching|answer|mouse|timer|ask/.test(t))return'sensing';if(/score|variable|list|item/.test(t))return'variables';if(/\+| - |\*|\/|>|<|and|or|random|join/.test(t))return'operators';return'motion'};
function mediaHtml(x){let out='';if(x.imageUrl)out+=`<figure class="inline-media"><img src="${esc(x.imageUrl)}" alt="ภาพด่าน ${esc(x.title)}" loading="lazy"></figure>`;if(x.videoUrl){const u=String(x.videoUrl),m=u.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{6,})/);out+=m?`<div class="video-wrap"><iframe src="https://www.youtube-nocookie.com/embed/${m[1]}" title="วิดีโอด่าน" allowfullscreen></iframe></div>`:`<video class="inline-video" controls src="${esc(u)}"></video>`}if(x.audioUrl)out+=`<audio class="inline-audio" controls src="${esc(x.audioUrl)}"></audio>`;return out}
const blockHtml=(b,i,source=true)=>`<button class="scratch-block ${categoryOf(b)} ${/when |when green flag/.test(b.toLowerCase())?'hat':''}" data-index="${i}" data-source="${source?'palette':'workspace'}" data-en="${esc(b)}"><span class="block-label">${esc(b)}</span><span class="english-read" aria-hidden="true">🔊</span></button>`;
const categoryMeta={motion:['Motion','#4c97ff'],looks:['Looks','#9966ff'],sound:['Sound','#cf63cf'],events:['Events','#ffbf00'],control:['Control','#ffab19'],sensing:['Sensing','#5cb1d6'],operators:['Operators','#59c059'],variables:['Variables','#ff8c1a'],myblocks:['My Blocks','#ff6680'],extensions:['Extensions','#0fbd8c']};
function groupedPalette(){const groups={};(level.blocks||[]).forEach((b,i)=>{const c=categoryOf(b);(groups[c]??=[]).push([b,i])});return `<div class="palette-groups">${Object.entries(groups).map(([c,items])=>`<section class="palette-group"><h4 class="palette-group-title"><i style="background:${categoryMeta[c]?.[1]||'#888'}"></i>${categoryMeta[c]?.[0]||c}</h4><div>${items.map(([b,i])=>blockHtml(b,i,true)).join('')}</div></section>`).join('')}</div>`}
function categoryKey(){return `<div class="category-key">${Object.entries(categoryMeta).map(([c,[name,color]])=>`<span style="background:${color}">${name}</span>`).join('')}</div>`}
function render(){if(missingLessons.length||prerequisiteMissing){const names=missingLessons.map(id=>allLessons.find(x=>x.id===id)?.title||id);const pre=prerequisiteMissing?(allLevels.find(x=>x.id===level.prerequisiteLevelId)?.title||level.prerequisiteLevelId):'';game.innerHTML=`<h1>🔒 ด่านยังไม่ปลดล็อก</h1><p>กรุณา${names.length?' เรียนบทเรียน '+names.map(x=>'“'+esc(x)+'”').join(', '):''}${pre?' และผ่านด่าน “'+esc(pre)+'”':''} ก่อน</p><div class="actions"><a class="button" href="./learn.html${missingLessons[0]?'?lesson='+encodeURIComponent(missingLessons[0]):''}">ไปหน้าบทเรียน</a><a class="button secondary" href="./adventure.html">กลับแผนที่ด่าน</a></div>`;return}game.innerHTML=`<div class="game-toolbar"><div><span class="badge">ด่าน ${level.order}</span><h1>${esc(level.title)}</h1></div><div><span class="game-stat">❤️ ${hearts}</span><span class="game-stat" id="timer">⏱️ 0</span></div></div><p>${esc(level.prompt)}</p>${mediaHtml(level)}${lesson?`<p><strong>ความรู้ก่อนเล่น:</strong> ${esc(lesson.summary)}</p>`:''}<div class="actions"><button id="read-all">🔊 อ่านคำสั่งทั้งหมด</button><button id="read-en" class="secondary">🇬🇧 Read English blocks</button></div><h3>Scratch Block Palette</h3>${categoryKey()}${groupedPalette()}<h3>Code Area — แตะบล็อกตามลำดับ</h3><div class="workspace">${selected.map((b,i)=>blockHtml(b,i,false)).join('')||'<span>เลือกบล็อกจากด้านบน</span>'}</div><div class="actions"><button id="check">✅ ตรวจคำตอบ</button><button id="undo" class="secondary">↩️ ย้อนกลับ</button><button id="clear" class="secondary">🗑️ ล้างพื้นที่</button><a class="button secondary" href="./adventure.html">ออกจากด่าน</a></div><div id="feedback"></div>`;
 document.querySelectorAll('[data-source="palette"]').forEach(b=>b.onclick=e=>{if(e.target.closest('.english-read')){e.stopPropagation();speak(b.dataset.en,'en-US');return}selected.push(level.blocks[+b.dataset.index]);render()});
 document.querySelectorAll('[data-source="workspace"]').forEach(b=>b.onclick=e=>{if(e.target.closest('.english-read')){e.stopPropagation();speak(b.dataset.en,'en-US');return}selected.splice(+b.dataset.index,1);render()});
 document.querySelector('#undo').onclick=()=>{selected.pop();render()};document.querySelector('#clear').onclick=()=>{selected=[];render()};document.querySelector('#read-all').onclick=()=>speakMixed(`ด่าน ${level.order} ${level.title} ${level.prompt}`,(level.blocks||[]).join('. '));document.querySelector('#read-en').onclick=()=>speak((level.blocks||[]).join('. '),'en-US',{rate:.68});document.querySelector('#check').onclick=check;
}
function normalize(a){return String(a).toLowerCase().replace(/\s+/g,' ').trim()}
function check(){const answer=level.answer||[];let ok=false;if(level.type==='quiz')ok=selected.length>0&&answer.map(normalize).includes(normalize(selected.at(-1)));else ok=answer.length===selected.length&&answer.every((x,i)=>normalize(x)===normalize(selected[i]));const f=document.querySelector('#feedback');if(ok){const sec=Math.round((Date.now()-start)/1000),stars=!level.timeLimit?3:sec<=level.stars.three?3:sec<=level.stars.two?2:1;const progress=JSON.parse(localStorage.getItem('scratchAR.levelProgress')||'{}');progress[level.id]={completed:true,stars,score:stars*100,completedAt:new Date().toISOString()};localStorage.setItem('scratchAR.levelProgress',JSON.stringify(progress));f.className='feedback good';f.innerHTML=`เก่งมาก! คำตอบถูกต้อง ได้ ${stars} ดาว <div class="actions"><a class="button" href="./adventure.html">ไปด่านถัดไป</a></div>`;speakMixed(`เก่งมาก คำตอบถูกต้อง คุณได้ ${stars} ดาว`,'Excellent! Your code is correct.')}else{hearts--;f.className='feedback bad';f.textContent=hearts>0?'ยังไม่ถูก ลองตรวจลำดับบล็อกอีกครั้ง':'หัวใจหมดแล้ว กดล้างพื้นที่และลองใหม่';speakMixed('ยังไม่ถูก ลองตรวจลำดับบล็อกอีกครั้ง','Not quite. Check the order of the blocks and try again.');if(hearts<=0)hearts=level.hearts||3;setTimeout(render,1100)}}
render();speakMixed(`เริ่มด่าน ${level.title} ${level.prompt}`,(level.blocks||[]).join('. '));setInterval(()=>{const t=document.querySelector('#timer');if(t)t.textContent=`⏱️ ${Math.round((Date.now()-start)/1000)}`},1000);
